### ISSUE TITLE
Adapting eslint config to prettier (was: Linting command files filter is wrong)

### ISSUE THREAD

**Issue by sneridagh** [plone/plone-react#100]
It doesn't have the correct filter, it misses to catch the *.jsx files.

Try:
`./node_modules/eslint/bin/eslint.js -c .eslintrc src/**/*.jsx`

**Comment by tisto** [comment]
We are currently using the Airbnb setting for eslint. Though, we should use an eslint config that does not conflict with prettier. There are lots of options, such as: https://github.com/prettier/eslint-config-prettier

We have to try them out and find one that works for us...

**Comment by nileshgulia1** [comment]
I'm on it :)

**Comment by sneridagh** [comment]
@nileshgulia1 thx, we will take a look!

**Comment by nileshgulia1** [comment]
Fixed by #128
