### ISSUE TITLE
GSoC 2018 Ideas for plone-react

### ISSUE THREAD

**Issue by tisto** [plone/plone-react#115]
Notes from our discussion at the plone-react sprint in Bonn (@sneridagh @robgietema @tisto):

# Implement Pastanaga / plone-react Widgets

- Reference widget (autocomplete + content browsing within autocomplete)
- Collection / Querystring Widget (See edit view of the Collection type in Plone)
- DateTime widget
- Date widget
- Time widget
- Workflow dropdown

In addition to implementing those widgets the GSoC 2018 could include:

- Documentation of plone-react
- Styling of Pastanaga widgets (e.g. select workflow dropdown styling)

**Comment by singhrohan62** [comment]
Hey @tisto I am applying for the GSoC 2018 and wish to contribute in this project.As I was reading the Plone documentation, I came to know that I cannot contribute in any project of Plone unless I sign the contributor agreement. I know it seems like an irrelevant question, but do I need to sign the agreement to participate in the GSoC 2018 through this organization or can it be done later? Kindly reply ASAP. Thank you!

**Comment by tisto** [comment]
You don't need to sign the contributor agreement to apply for GSoC. Might be desirable if you get accepted though. 

Von meinem iPhone gesendet
