### ISSUE TITLE
Current state of plone-react & production readiness

### ISSUE THREAD

**Issue by ezvirtual** [plone/plone-react#129]
Hey there,
I was hoping someone could give me a bit of advice on plone-react.

Are people currently using this package in production? If so, does anyone have some publicly accessible examples of this?

Is it worth doing some testing with this as a relative JS-noob?

Basically I'm wondering if it's worth doing some testing looking to use plone-react for a client site update or if it's too soon for this / not a good use time at this point.

Thanks heaps for all of the work that has gone in to this and in advance for anyone taking the time to offer some advice.

**Comment by robgietema** [comment]
We have build one production site using plone-react so you can definately use this in production. That being said I would say it is all still in alpha stage so not all functionality of Plone is implemented yet but all the basics are there.

If you have some knowledge of react you should be able to implement a website using plone-react yourself and if you need any help let me know.
