### ISSUE TITLE
Pastanaga Editor: Video upload does not show up on view

### ISSUE THREAD

**Issue by tisto** [plone/plone-react#198]
1) Go to https://plone-react.kitconcept.io/front-page
2) Login
3) Edit front page and add new video tile
-> video shows up properly
4) Hit save button
-> video does not show up (see screenshot)

![welcome to plone](https://user-images.githubusercontent.com/632105/42038185-9def8200-7aea-11e8-894a-df4f0be2c6bb.png)

**Comment by robgietema** [comment]
Fixed in #204
