### ISSUE TITLE
View/Route detection to prevent failed fetchs from backend

### ISSUE THREAD

**Issue by sneridagh** [plone/plone-react#88]
If you navigate to the a view or route (like the contact form) located in the root, then it tries to GET the content in the backend, and fails.

**Comment by robgietema** [comment]
The view name will be chopped of the url and so it will fetch the content of the root to render de view (which is correct). The view name does need to be there in the helper. Maybe it's better to switch to the `@@` notation in the frontend also.

**Comment by davilima6** [comment]
I belive this is already in place, let's reopen if not:

* https://github.com/plone/plone-react/blob/778e77bff4821d8d3a1f5de1d229f846101a47a6/src/helpers/Url/Url.js#L14-L36

(the example, contact form, is still not implemented but when it is we'll add to the list above)
