### ISSUE TITLE
Issue with prettier configuration

### ISSUE THREAD

**Issue by nileshgulia1** [plone/plone-react#89]
Everytime we change code we get unexpected diffs while creating a PR. I think prettier or linter needs to be re-configured.

**Comment by nileshgulia1** [comment]
Are we using pre-commit hooks(with husky or lint-staged) here? I guess not, may be the problem is with developers text editor we should add something like `.editorconfig` and configure code style for all the developers.

**Comment by robgietema** [comment]
It's actually yarn (and npm) who mess with the format. When you do a "yarn add <something>", yarn will reformat the package.json file. When you do add something using yarn add make sure you save the package.json again using prettier settings.
