### ISSUE TITLE
Error reporting on failed backend calls

### ISSUE THREAD

**Issue by tisto** [plone/plone-react#92]
When working with plone-react I did some calls on non-existing backend endpoints (typo in the path). I had to go through the reducers, the API middleware and debug a lot until I figured out the simple solution to my problem. React 16 will give us error boundaries for components. How can we improve the API middleware to give meaningful error messages?

I plan to look into that. What are best practices to report errors on a redux middleware? Any pointers would be appreciated. @robgietema @sneridagh

**Comment by tisto** [comment]
Helpful blog post from Sentry: https://blog.sentry.io/2016/08/24/redux-middleware-error-logging

**Comment by tisto** [comment]
redux-reporter, a redux middleware for reporting to Sentry et. al.: https://www.npmjs.com/package/redux-reporter

**Comment by nileshgulia1** [comment]
@tisto  How about using API middleware like [redux-saga](https://www.npmjs.com/package/redux-saga) for playing with error boundaries?

**Comment by robgietema** [comment]
Fixed by #106
